#!/bin/sh

h=20
rurl="https://kernel.ubuntu.com/~kernel-ppa/mainline/"

kurl=$(curl -sSL "$rurl" | sed "s/\"/\n/g" | grep ^v | \
        sed 's/-rc/.0rc/g' | \
        sed 's/\./.00/g' | \
        sort | \
        sed 's/\.00/./g' | sed 's/.0rc/-rc/g' | tac -)
if [ "$1" = "-l" ] ; then kurl=$rurl$(echo "$kurl" | sed 1q)
else kurl=$rurl$(echo "$kurl" | dmenu -l "$h") || exit 0 ; fi

raw=$(curl -sSL "$kurl")

echo "$raw" | grep "Build for amd64 failed" > /dev/null && \
        echo "This kernel's build failed for amd64!" &&
        exit 1

raw=$(echo "$raw" | sed "s/\"/\n/g" | grep deb | grep -v "<")
araw=$(echo "$raw" | grep amd64 | grep generic)

udpkg "$kurl$(echo "$araw" | grep linux-modules- | sed 1q)"
udpkg "$kurl$(echo "$raw" | grep all | grep linux-headers- | sed 1q)"
udpkg "$kurl$(echo "$araw" | grep linux-headers- | sed 1q)"
udpkg "$kurl$(echo "$araw" | grep linux-image-unsigned- | sed 1q)"
