#!/bin/sh

selector="dmenu -l 20"
url="https://kernel.ubuntu.com/~kernel-ppa/mainline/"

kurl=$(curl -sSL "$url" | sed 's/\"/\n/g' | grep ^v | sed 's/^v\(.*\)\/$/\1.00/' | sort -V | sed 's/\.00//' | awk '{print "v" $0 "/" }' | tac -)
[ "$1" = "-l" ] && selector="sed 1q"
kurl=$url$(echo "$kurl" | $selector) || exit 0

raw=$(curl -sSL "$kurl")

echo "$raw" | grep "Build for amd64 failed" > /dev/null && \
        echo "This kernel's build failed for amd64!" &&
        exit 1

raw=$(echo "$raw" | sed "s/\"/\n/g" | grep deb | grep -v "<")
araw=$(echo "$raw" | grep amd64 | grep generic)

udpkg "$kurl$(echo "$araw" | grep linux-modules- | sed 1q)"
udpkg "$kurl$(echo "$raw" | grep all | grep linux-headers- | sed 1q)"
udpkg "$kurl$(echo "$araw" | grep linux-headers- | sed 1q)"
udpkg "$kurl$(echo "$araw" | grep linux-image-unsigned- | sed 1q)"
